import {IStudent} from "./students";

export const STUDENTS: IStudent[] = [
  { reg_num: '111',
    fio: 'Иванов',
    birth_date: 'gfg',
    group_name: 'ГМ',
    sex: 'м',
    kurs: '3',
    spec_name: 'gfg',
    qualification_name: 'Бакалавриат',
    fo_name: 'gfg',
    fac_code: 'gfg',
    name_stat: 'gfg',
    compensation_type_code: 'gfg',
    student_id: 111111},
  { reg_num: '222',
    fio: 'Петров',
    birth_date: 'jhjkj',
    group_name: 'НФ',
    sex: 'м',
    kurs: '4',
    spec_name: 'jhjkj',
    qualification_name: 'Специалитет',
    fo_name: 'jhjkj',
    fac_code: 'jhjkj',
    name_stat: 'jhjkj',
    compensation_type_code: 'jhjkj',
    student_id: 222222},
  { reg_num: '333',
    fio: 'Алексеева',
    birth_date: 'htfh',
    group_name: 'ЛР',
    sex: 'ж',
    kurs: '2',
    spec_name: 'htfh',
    qualification_name: 'Магистратура',
    fo_name: 'htfh',
    fac_code: 'htfh',
    name_stat: 'htfh',
    compensation_type_code: 'htfh',
    student_id: 333333}
];
